sudo: required

language: generic

services:
 - docker

before_install:
 - echo "start creating an image with dockerfile"
 - docker build -t kwonmoonsung/docker-react-app -f dockerfile.dev .

script:
 - docker run -e CI=true kwonmoonsung/docker-react-app npm run test -- --coverage

after_success:
 - echo "Test success"